export const RECOVERY_TIPS: string[] = [
  'Aim for 7-9 hours of sleep tonight — recovery happens while you rest, not just while you train.',
  'Hydration affects more than performance. Try to drink water consistently throughout the day.',
  'Gentle movement today helps clear muscle soreness faster than sitting still.',
  'Protein intake matters on rest days too — it fuels the repair your muscles are doing right now.',
  'A short walk outside can lower stress hormones and support recovery.',
  'Stretching tight areas for even five minutes can improve how you feel tomorrow.',
  'Recovery is when adaptation happens. Today is part of the training, not a break from it.',
  'Foam rolling before bed can help reduce next-day stiffness.',
  'Try to keep screen time low before sleep — it improves sleep quality, which improves recovery.',
  'A warm shower or bath can help relax tight muscles after a hard training block.',
  'Mental recovery matters as much as physical — take a moment today to switch off.',
  'Consistency beats intensity. Showing up for easy days builds the base for hard days.',
  'Light cardio increases blood flow to sore muscles, speeding up the clearing of waste products.',
  'Don\'t skip your warm-up tomorrow — today\'s recovery sets the stage for it.',
  'Eating enough carbohydrates on rest days helps replenish glycogen stores.',
  'Breathing exercises can lower your resting heart rate and improve nervous system recovery.',
  'Soreness is normal, but sharp pain is not — listen to the difference.',
  'A consistent sleep schedule, even on rest days, helps regulate your body clock.',
  'Magnesium-rich foods like nuts and leafy greens may support muscle relaxation.',
  'Today is a great day to prep meals for the week ahead.',
  'Mobility work is most effective when done consistently, not just when you feel tight.',
  'Your nervous system needs recovery too — an easy day helps you train harder tomorrow.',
  'Take five minutes to reflect on what went well this week.',
  'Gentle yoga or stretching can improve circulation without adding fatigue.',
  'Cold exposure (like a cool shower) may help reduce inflammation for some people.',
  'Spending time outdoors, even briefly, can improve mood and lower stress.',
  'Plan tomorrow\'s session today so you can walk in with a clear focus.',
  'Recovery isn\'t passive — it\'s an active part of getting stronger.',
]
