import { Link } from 'react-router-dom'
import { LegalPage, LegalSection } from '@/components/marketing/LegalPage'

export function TermsOfService() {
  return (
    <LegalPage title="Terms of Service" lastUpdated="June 2026">
      <LegalSection heading="1. Acceptance of Terms">
        <p style={{ marginBottom: 12 }}>
          By creating an account and using GRYT, you agree to these Terms of Service and our Privacy Policy. If you
          do not agree, do not use GRYT. These terms constitute a legally binding agreement between you and
          Catalyst Digital Operations (Pty) Ltd.
        </p>
      </LegalSection>

      <LegalSection heading="2. Eligibility">
        <p style={{ marginBottom: 12 }}>
          You must be at least 18 years old to use GRYT. By using GRYT, you confirm that you meet this requirement.
        </p>
      </LegalSection>

      <LegalSection heading="3. Health and Safety Disclaimer">
        <p style={{ marginBottom: 12 }}>
          GRYT provides personalised training programmes generated by artificial intelligence. These programmes
          are not a substitute for professional medical or fitness advice. Before starting any training programme,
          particularly if you have a pre-existing medical condition, injury, or health concern, consult a qualified
          medical professional.
        </p>
        <p style={{ marginBottom: 12 }}>By using GRYT, you acknowledge that:</p>
        <ul style={{ paddingLeft: 20, marginBottom: 12 }}>
          <li style={{ marginBottom: 6 }}>Physical exercise carries inherent risk of injury</li>
          <li style={{ marginBottom: 6 }}>You are responsible for exercising within your own physical limits</li>
          <li style={{ marginBottom: 6 }}>
            GRYT&apos;s AI-generated programmes are designed for generally healthy adults and may not be
            appropriate for your specific circumstances
          </li>
          <li style={{ marginBottom: 6 }}>
            GRYT is not liable for any injury, illness, or health consequence resulting from following a GRYT
            training programme
          </li>
        </ul>
      </LegalSection>

      <LegalSection heading="4. Your Account">
        <p style={{ marginBottom: 12 }}>
          You are responsible for maintaining the security of your account credentials. You must not share your
          account with any other person. You must notify us immediately at info@gryt.co.za if you suspect
          unauthorised access to your account. We reserve the right to terminate accounts that violate these terms.
        </p>
      </LegalSection>

      <LegalSection heading="5. Subscription and Payment">
        <p style={{ marginBottom: 12 }}>
          GRYT is offered on a subscription basis. By subscribing, you authorise Catalyst Digital Operations (Pty)
          Ltd to charge your payment method on a recurring basis at the interval you selected (monthly or
          annually). Payments are processed by Paystack. Your subscription will automatically renew at the end of
          each billing period unless you cancel it in advance through the Settings section of the app.
        </p>
        <p style={{ marginBottom: 12 }}>
          For details on refunds and cancellations, please refer to our{' '}
          <Link to="/refund-policy" style={{ color: 'var(--color-text-primary)' }}>
            Refund Policy
          </Link>
          .
        </p>
      </LegalSection>

      <LegalSection heading="6. Free Trial">
        <p style={{ marginBottom: 12 }}>
          GRYT offers a 7-day free trial for new users. No payment is taken during the trial. At the end of the
          trial, your subscription will begin and your payment method will be charged unless you have cancelled
          before the trial ends.
        </p>
      </LegalSection>

      <LegalSection heading="7. Acceptable Use">
        <p style={{ marginBottom: 12 }}>You agree not to:</p>
        <ul style={{ paddingLeft: 20, marginBottom: 12 }}>
          <li style={{ marginBottom: 6 }}>Use GRYT for any unlawful purpose</li>
          <li style={{ marginBottom: 6 }}>Attempt to gain unauthorised access to any part of GRYT&apos;s systems</li>
          <li style={{ marginBottom: 6 }}>Reverse engineer, decompile, or copy any part of GRYT</li>
          <li style={{ marginBottom: 6 }}>Use GRYT to distribute spam or malicious content</li>
          <li style={{ marginBottom: 6 }}>Misrepresent your identity or impersonate any person</li>
        </ul>
      </LegalSection>

      <LegalSection heading="8. Intellectual Property">
        <p style={{ marginBottom: 12 }}>
          All content within GRYT — including but not limited to training programmes, exercise descriptions,
          coaching content, and the Kwazi AI persona — is the intellectual property of Catalyst Digital Operations
          (Pty) Ltd. You may not reproduce, distribute, or create derivative works from any GRYT content without
          our prior written consent.
        </p>
      </LegalSection>

      <LegalSection heading="9. Limitation of Liability">
        <p style={{ marginBottom: 12 }}>
          To the maximum extent permitted by South African law, Catalyst Digital Operations (Pty) Ltd&apos;s total
          liability to you for any claim arising from your use of GRYT shall not exceed the amount you paid to us
          in the 3 months preceding the claim. We are not liable for any indirect, incidental, special, or
          consequential damages, including but not limited to loss of data, loss of revenue, or personal injury,
          except where such liability cannot be excluded under the Consumer Protection Act or POPIA.
        </p>
      </LegalSection>

      <LegalSection heading="10. Your Rights Under the Consumer Protection Act">
        <p style={{ marginBottom: 12 }}>
          Nothing in these Terms limits or excludes rights you are entitled to under the Consumer Protection Act 68
          of 2008. If any provision of these Terms conflicts with the CPA, the CPA shall prevail.
        </p>
      </LegalSection>

      <LegalSection heading="11. Termination">
        <p style={{ marginBottom: 12 }}>
          We reserve the right to suspend or terminate your account if you breach these Terms. You may terminate
          your account at any time by contacting us at info@gryt.co.za. Termination does not entitle you to a
          refund except as provided in our Refund Policy.
        </p>
      </LegalSection>

      <LegalSection heading="12. Governing Law">
        <p style={{ marginBottom: 12 }}>
          These Terms are governed by the laws of the Republic of South Africa. Any dispute arising from these
          Terms shall be subject to the jurisdiction of the South Gauteng High Court, Johannesburg.
        </p>
      </LegalSection>

      <LegalSection heading="13. Changes to These Terms">
        <p style={{ marginBottom: 12 }}>
          We may update these Terms from time to time. We will notify you of material changes by email or through
          the app at least 20 business days before they take effect, in accordance with the CPA. Your continued
          use of GRYT after the effective date constitutes acceptance of the updated Terms.
        </p>
      </LegalSection>

      <LegalSection heading="14. Contact">
        <p style={{ marginBottom: 0 }}>Catalyst Digital Operations (Pty) Ltd</p>
        <p style={{ marginBottom: 0 }}>Rosewood Road, Broadacres, Fourways, 2021</p>
        <p style={{ marginBottom: 0 }}>info@gryt.co.za</p>
      </LegalSection>
    </LegalPage>
  )
}
