import type { Archetype, Equipment, Focus, Phase } from '@/types/plan.types'
import type { ExperienceLevel } from '@/types/onboarding'

export type ConditioningType = 'steady_state' | 'interval' | 'sprint' | 'circuit' | 'tabata'

// squat/hinge/push_horizontal/push_vertical/pull_horizontal/pull_vertical are
// the patterns selectExercises.ts caps per session (Issue 1) — stacking two
// heavy lifts of the same pattern in one session is a real same-muscle-group
// overload risk, not just a variety complaint. carry/core/conditioning/other/
// pull_accessory are never capped: HYROX station/circuit work (is_hyrox_station:
// true) is deliberately tagged conditioning/carry/other so the per-session
// pattern cap never conflicts with station-circuit content that's meant to
// appear as a themed set (Issue 2); pull_accessory (shoulder health work, e.g.
// face pulls) and core are never capped for the same reason core has its own
// dedicated core_stability section.
export type MovementPattern =
  | 'squat'
  | 'hinge'
  | 'push_horizontal'
  | 'push_vertical'
  | 'pull_horizontal'
  | 'pull_vertical'
  | 'pull_accessory'
  | 'carry'
  | 'core'
  | 'conditioning'
  | 'other'

export interface LibraryExercise {
  name: string
  category: Focus
  equipment: Equipment[]
  archetypes: Archetype[]
  phases: Phase[]
  default_sets: number
  default_reps: number | string
  default_rest_seconds: number
  default_rpe: number
  coaching_cues: string[]
  home_alternative?: string
  is_compound: boolean
  conditioning_type?: ConditioningType
  movement_pattern: MovementPattern
  // True only for exercises in the HYROX / HYROX STATIONS sections below —
  // selectExercises.ts uses this to build the station-based main body of a
  // HYROX Competitor session, distinct from the supporting strength lifts.
  is_hyrox_station?: boolean
  // undefined = available to all experience levels (default)
  min_experience?: ExperienceLevel
}

const ALL_ARCHETYPES: Archetype[] = [
  'Endurance Athlete',
  'Strength Athlete',
  'Hybrid Performer',
  'Bodybuilder',
  'General Fitness',
  'Mobility Focus',
  'Fat Loss',
  'Functional Strength & Conditioning',
  'Athletic Performance',
  'HYROX Competitor',
]

const ALL_EQUIPMENT: Equipment[] = ['full_gym', 'home_gym', 'bodyweight']

const ALL_PHASES: Phase[] = ['foundation', 'build', 'peak', 'deload']
const NO_DELOAD: Phase[] = ['foundation', 'build', 'peak']

export const EXERCISE_LIBRARY: LibraryExercise[] = [
  // ───────────── COMPOUNDS ─────────────
  {
    name: 'Barbell Back Squat',
    category: 'lower',
    equipment: ['full_gym'],
    archetypes: ['Strength Athlete', 'Bodybuilder', 'Hybrid Performer', 'Athletic Performance', 'General Fitness', 'Fat Loss', 'Functional Strength & Conditioning'],
    phases: ALL_PHASES,
    default_sets: 4,
    default_reps: 6,
    default_rest_seconds: 150,
    default_rpe: 7,
    coaching_cues: ['Brace your core before unracking', 'Drive knees out over toes', 'Keep chest tall through the descent'],
    is_compound: true,
    movement_pattern: 'squat',
    min_experience: 'advanced',
  },
  {
    name: 'Front Squat',
    category: 'lower',
    equipment: ['full_gym'],
    archetypes: ['Strength Athlete', 'Hybrid Performer', 'Athletic Performance', 'Functional Strength & Conditioning', 'HYROX Competitor'],
    phases: ALL_PHASES,
    default_sets: 4,
    default_reps: 6,
    default_rest_seconds: 150,
    default_rpe: 7,
    coaching_cues: ['Elbows high, bar resting on front delts', 'Sit straight down between your hips', 'Drive up through a tall torso — this transfers directly to wall ball depth'],
    is_compound: true,
    movement_pattern: 'squat',
    min_experience: 'advanced',
  },
  {
    name: 'Romanian Deadlift',
    category: 'lower',
    equipment: ['full_gym', 'home_gym'],
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: 8,
    default_rest_seconds: 120,
    default_rpe: 7,
    coaching_cues: ['Hinge at the hips, soft knees', 'Keep the bar close to your legs', 'Feel the stretch in your hamstrings'],
    is_compound: true,
    movement_pattern: 'hinge',
  },
  {
    name: 'Conventional Deadlift',
    category: 'lower',
    equipment: ['full_gym'],
    archetypes: ['Strength Athlete', 'Hybrid Performer', 'Athletic Performance', 'General Fitness', 'Fat Loss', 'Functional Strength & Conditioning'],
    phases: ALL_PHASES,
    default_sets: 4,
    default_reps: 5,
    default_rest_seconds: 180,
    default_rpe: 8,
    coaching_cues: ['Set your lats before the pull', 'Push the floor away', 'Keep the bar path vertical'],
    is_compound: true,
    movement_pattern: 'hinge',
    min_experience: 'intermediate',
  },
  {
    name: 'Trap Bar Deadlift',
    category: 'lower',
    equipment: ['full_gym'],
    archetypes: ['Strength Athlete', 'Hybrid Performer', 'Athletic Performance', 'General Fitness', 'Fat Loss', 'Functional Strength & Conditioning', 'HYROX Competitor'],
    phases: ALL_PHASES,
    default_sets: 4,
    default_reps: 6,
    default_rest_seconds: 150,
    default_rpe: 7,
    coaching_cues: ['Drive through mid-foot', 'Stand tall at the top, no lean back', 'Control the descent'],
    is_compound: true,
    movement_pattern: 'hinge',
    min_experience: 'intermediate',
  },
  {
    name: 'Bench Press',
    category: 'upper_push',
    equipment: ['full_gym'],
    archetypes: ['Bodybuilder', 'Strength Athlete', 'Hybrid Performer', 'Athletic Performance', 'General Fitness', 'Fat Loss', 'Functional Strength & Conditioning'],
    phases: ALL_PHASES,
    default_sets: 4,
    default_reps: 6,
    default_rest_seconds: 120,
    default_rpe: 7,
    coaching_cues: ['Pull shoulder blades together and down', 'Lower the bar with control to your chest', 'Drive feet into the floor'],
    is_compound: true,
    movement_pattern: 'push_horizontal',
  },
  {
    name: 'Overhead Press',
    category: 'upper_push',
    equipment: ['full_gym', 'home_gym'],
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: 8,
    default_rest_seconds: 90,
    default_rpe: 7,
    coaching_cues: ['Brace your core, ribs down', 'Press in a straight line overhead', 'Squeeze glutes to protect the lower back'],
    is_compound: true,
    movement_pattern: 'push_vertical',
    min_experience: 'advanced',
  },
  {
    name: 'Barbell Row',
    category: 'upper_pull',
    equipment: ['full_gym', 'home_gym'],
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 4,
    default_reps: 8,
    default_rest_seconds: 90,
    default_rpe: 7,
    coaching_cues: ['Hinge to roughly 45 degrees', 'Pull the bar to your lower ribs', 'Avoid jerking the weight up'],
    is_compound: true,
    movement_pattern: 'pull_horizontal',
  },
  {
    name: 'Pull-Up',
    category: 'upper_pull',
    equipment: ['full_gym', 'home_gym'],
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 4,
    default_reps: 6,
    default_rest_seconds: 90,
    default_rpe: 7,
    coaching_cues: ['Start from a full hang', 'Drive elbows down and back', 'Avoid kipping unless trained'],
    home_alternative: 'Band-assisted pull-up or inverted row',
    is_compound: true,
    movement_pattern: 'pull_vertical',
    min_experience: 'intermediate',
  },
  {
    name: 'Chin-Up',
    category: 'upper_pull',
    equipment: ['full_gym', 'home_gym'],
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 4,
    default_reps: 6,
    default_rest_seconds: 90,
    default_rpe: 7,
    coaching_cues: ['Underhand grip, shoulder width', 'Drive elbows to your hips', 'Control the lowering phase'],
    home_alternative: 'Band-assisted chin-up or inverted row',
    is_compound: true,
    movement_pattern: 'pull_vertical',
    min_experience: 'intermediate',
  },
  {
    name: 'Dumbbell Lunge',
    category: 'lower',
    equipment: ['full_gym', 'home_gym', 'bodyweight'],
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: 10,
    default_rest_seconds: 60,
    default_rpe: 6,
    coaching_cues: ['Step out to a comfortable distance', 'Lower the back knee under control', 'Drive through the front heel to stand'],
    home_alternative: 'Bodyweight lunge',
    is_compound: true,
    movement_pattern: 'squat',
  },
  {
    name: 'Bulgarian Split Squat',
    category: 'lower',
    equipment: ['full_gym', 'home_gym', 'bodyweight'],
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: 8,
    default_rest_seconds: 90,
    default_rpe: 7,
    coaching_cues: ['Rear foot elevated on a bench', 'Keep most of the weight on the front leg', 'Descend until the rear knee nears the floor'],
    home_alternative: 'Bodyweight split squat',
    is_compound: true,
    movement_pattern: 'squat',
    min_experience: 'intermediate',
  },
  {
    name: 'Hip Thrust',
    category: 'lower',
    equipment: ['full_gym', 'home_gym'],
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: 10,
    default_rest_seconds: 90,
    default_rpe: 7,
    coaching_cues: ['Shoulder blades on the bench', 'Drive hips up, squeeze glutes hard at the top', 'Keep ribs down, avoid over-arching'],
    home_alternative: 'Single-leg glute bridge',
    is_compound: true,
    movement_pattern: 'hinge',
  },
  {
    name: 'Goblet Squat',
    category: 'lower',
    equipment: ['full_gym', 'home_gym', 'bodyweight'],
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: 12,
    default_rest_seconds: 60,
    default_rpe: 6,
    coaching_cues: ['Hold the weight close to your chest', 'Sit between your knees, elbows inside', 'Keep heels planted'],
    home_alternative: 'Bodyweight squat',
    is_compound: true,
    movement_pattern: 'squat',
  },
  {
    name: 'Reverse Lunge',
    category: 'lower',
    equipment: ['full_gym', 'home_gym', 'bodyweight'],
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: 10,
    default_rest_seconds: 60,
    default_rpe: 6,
    coaching_cues: ['Step back under control', 'Keep front shin near vertical', 'Push through the front foot to return'],
    is_compound: true,
    movement_pattern: 'squat',
  },
  {
    name: 'Push-Up',
    category: 'upper_push',
    equipment: ['full_gym', 'home_gym', 'bodyweight'],
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: 15,
    default_rest_seconds: 60,
    default_rpe: 6,
    coaching_cues: ['Keep a straight line from head to heels', 'Lower chest close to the floor', 'Press through the full hand'],
    is_compound: true,
    movement_pattern: 'push_horizontal',
  },
  {
    name: 'Dip',
    category: 'upper_push',
    equipment: ['full_gym', 'home_gym'],
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: 10,
    default_rest_seconds: 90,
    default_rpe: 7,
    coaching_cues: ['Lean slightly forward', 'Lower until shoulders feel a stretch', 'Press back up to lockout'],
    home_alternative: 'Close-grip push-up',
    is_compound: true,
    movement_pattern: 'push_horizontal',
    min_experience: 'intermediate',
  },

  // ───────────── PLYOMETRIC / POWER ─────────────
  {
    name: 'Box Jump',
    category: 'plyometric',
    equipment: ['full_gym', 'home_gym'],
    archetypes: ['Athletic Performance', 'Hybrid Performer', 'Strength Athlete'],
    phases: NO_DELOAD,
    default_sets: 4,
    default_reps: 5,
    default_rest_seconds: 90,
    default_rpe: 7,
    coaching_cues: ['Stand tall before each rep', 'Land softly with bent knees', 'Step down, don’t jump down'],
    is_compound: false,
    movement_pattern: 'other',
    min_experience: 'intermediate',
  },
  {
    name: 'Broad Jump',
    category: 'plyometric',
    equipment: ALL_EQUIPMENT,
    archetypes: ['Athletic Performance', 'Hybrid Performer', 'Strength Athlete'],
    phases: NO_DELOAD,
    default_sets: 4,
    default_reps: 5,
    default_rest_seconds: 90,
    default_rpe: 7,
    coaching_cues: ['Swing arms back then explosively forward', 'Land with soft knees, stick the landing', 'Reset fully between reps'],
    is_compound: false,
    movement_pattern: 'other',
    min_experience: 'intermediate',
  },
  {
    name: 'Lateral Bound',
    category: 'lateral',
    equipment: ALL_EQUIPMENT,
    archetypes: ['Athletic Performance', 'Hybrid Performer'],
    phases: NO_DELOAD,
    default_sets: 3,
    default_reps: 6,
    default_rest_seconds: 60,
    default_rpe: 6,
    coaching_cues: ['Push off the outside leg', 'Stick the landing before bounding back', 'Stay low and athletic'],
    is_compound: false,
    movement_pattern: 'other',
    min_experience: 'intermediate',
  },
  {
    name: 'Depth Drop',
    category: 'plyometric',
    equipment: ['full_gym', 'home_gym'],
    archetypes: ['Athletic Performance', 'Strength Athlete'],
    phases: NO_DELOAD,
    default_sets: 3,
    default_reps: 5,
    default_rest_seconds: 120,
    default_rpe: 8,
    coaching_cues: ['Step off, don’t jump off the box', 'Absorb the landing through the hips', 'Reset fully before each rep'],
    is_compound: false,
    movement_pattern: 'other',
    min_experience: 'advanced',
  },
  {
    name: 'Tuck Jump',
    category: 'plyometric',
    equipment: ALL_EQUIPMENT,
    archetypes: ['Athletic Performance', 'Hybrid Performer'],
    phases: NO_DELOAD,
    default_sets: 3,
    default_reps: 8,
    default_rest_seconds: 90,
    default_rpe: 7,
    coaching_cues: ['Drive knees up toward your chest', 'Land softly and reset', 'Keep reps explosive, not rushed'],
    is_compound: false,
    movement_pattern: 'other',
    min_experience: 'intermediate',
  },
  {
    name: 'Single Leg Broad Jump',
    category: 'plyometric',
    equipment: ALL_EQUIPMENT,
    archetypes: ['Athletic Performance', 'Hybrid Performer'],
    phases: NO_DELOAD,
    default_sets: 3,
    default_reps: 5,
    default_rest_seconds: 90,
    default_rpe: 7,
    coaching_cues: ['Drive off one leg, land on the same leg', 'Stick the landing for 2 seconds', 'Match reps on both sides'],
    is_compound: false,
    movement_pattern: 'other',
    min_experience: 'intermediate',
  },
  {
    name: 'Reactive Box Jump',
    category: 'plyometric',
    equipment: ['full_gym', 'home_gym'],
    archetypes: ['Athletic Performance', 'Hybrid Performer'],
    phases: NO_DELOAD,
    default_sets: 3,
    default_reps: 5,
    default_rest_seconds: 120,
    default_rpe: 8,
    coaching_cues: ['Minimise ground contact time', 'Land and rebound immediately', 'Reset technique if quality drops'],
    is_compound: false,
    movement_pattern: 'other',
    min_experience: 'advanced',
  },
  {
    name: 'Medicine Ball Overhead Slam',
    category: 'power',
    equipment: ['full_gym', 'home_gym'],
    archetypes: ['Athletic Performance', 'Hybrid Performer', 'Bodybuilder', 'Fat Loss', 'Functional Strength & Conditioning'],
    phases: NO_DELOAD,
    default_sets: 4,
    default_reps: 8,
    default_rest_seconds: 60,
    default_rpe: 7,
    coaching_cues: ['Reach tall before the slam', 'Drive through the hips and core', 'Slam with full intent'],
    is_compound: false,
    movement_pattern: 'other',
    min_experience: 'intermediate',
  },
  {
    name: 'Rotational Med Ball Throw',
    category: 'power',
    equipment: ['full_gym', 'home_gym'],
    archetypes: ['Athletic Performance', 'Hybrid Performer'],
    phases: NO_DELOAD,
    default_sets: 3,
    default_reps: 8,
    default_rest_seconds: 60,
    default_rpe: 7,
    coaching_cues: ['Rotate from the hips, not just the arms', 'Throw explosively against the wall', 'Match reps each side'],
    is_compound: false,
    movement_pattern: 'other',
    min_experience: 'intermediate',
  },
  {
    name: 'Med Ball Slam',
    category: 'power',
    equipment: ['full_gym', 'home_gym'],
    archetypes: ['Athletic Performance', 'Hybrid Performer', 'Fat Loss', 'Functional Strength & Conditioning'],
    phases: NO_DELOAD,
    default_sets: 4,
    default_reps: 10,
    default_rest_seconds: 60,
    default_rpe: 7,
    coaching_cues: ['Full extension on the reach', 'Slam with maximum effort', 'Reset your stance every rep'],
    is_compound: false,
    movement_pattern: 'other',
    min_experience: 'intermediate',
  },

  // ───────────── LOADED CARRIES ─────────────
  {
    name: 'Farmers Walk',
    category: 'loaded_carry',
    equipment: ['full_gym', 'home_gym'],
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: '40m',
    default_rest_seconds: 90,
    default_rpe: 7,
    coaching_cues: ['Stand tall, brace your core', 'Keep shoulders down and back', 'Take controlled steps'],
    is_compound: false,
    movement_pattern: 'carry',
  },
  {
    name: 'Trap Bar Farmers Walk',
    category: 'loaded_carry',
    equipment: ['full_gym'],
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: '40m',
    default_rest_seconds: 90,
    default_rpe: 7,
    coaching_cues: ['Brace before lifting the bar', 'Walk with short, quick steps', 'Keep grip tight throughout'],
    is_compound: false,
    movement_pattern: 'carry',
  },
  {
    name: 'Suitcase Carry',
    category: 'loaded_carry',
    equipment: ['full_gym', 'home_gym'],
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: '30m each side',
    default_rest_seconds: 90,
    default_rpe: 7,
    coaching_cues: ['Resist leaning toward the loaded side', 'Keep shoulders level', 'Brace your obliques hard'],
    is_compound: false,
    movement_pattern: 'carry',
  },
  {
    name: 'Overhead Carry',
    category: 'loaded_carry',
    equipment: ['full_gym', 'home_gym'],
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: '20m',
    default_rest_seconds: 90,
    default_rpe: 7,
    coaching_cues: ['Stack the weight directly overhead', 'Brace your ribs down', 'Walk with control'],
    is_compound: false,
    movement_pattern: 'carry',
  },
  {
    name: 'Sled Push',
    category: 'loaded_carry',
    equipment: ['full_gym'],
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 4,
    default_reps: '20m',
    default_rest_seconds: 90,
    default_rpe: 8,
    coaching_cues: ['Drive with low, powerful steps', 'Keep a flat back, push through arms', 'Maintain consistent pace'],
    home_alternative: 'Load a bag, push for 10m',
    is_compound: false,
    movement_pattern: 'carry',
  },
  {
    name: 'Sled Pull',
    category: 'loaded_carry',
    equipment: ['full_gym'],
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 4,
    default_reps: '20m',
    default_rest_seconds: 90,
    default_rpe: 8,
    coaching_cues: ['Sit back into the harness', 'Drive the legs, pull with control', 'Keep tension throughout'],
    home_alternative: 'Resistance band sprint: anchor band, drive forward 10m',
    is_compound: false,
    movement_pattern: 'carry',
  },
  {
    name: 'Sandbag Clean & Press',
    category: 'loaded_carry',
    equipment: ['full_gym', 'home_gym'],
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 4,
    default_reps: 6,
    default_rest_seconds: 90,
    default_rpe: 7,
    coaching_cues: ['Keep the sandbag close to your body', 'Use your legs to drive it up', 'Press to full lockout overhead'],
    is_compound: false,
    movement_pattern: 'carry',
  },

  // ───────────── CONDITIONING / CARDIO ─────────────
  {
    name: 'Sprint Intervals 8×40m',
    category: 'sprint',
    equipment: ALL_EQUIPMENT,
    archetypes: ALL_ARCHETYPES,
    phases: NO_DELOAD,
    default_sets: 1,
    default_reps: '8×40m',
    default_rest_seconds: 60,
    default_rpe: 8,
    coaching_cues: ['Full recovery between reps', 'Drive arms and knees aggressively', "Maintain top-end form, don't over-stride"],
    is_compound: false,
    conditioning_type: 'sprint',
    movement_pattern: 'conditioning',
    min_experience: 'intermediate',
  },
  {
    name: 'Sprint Intervals 6×60m',
    category: 'sprint',
    equipment: ALL_EQUIPMENT,
    archetypes: ALL_ARCHETYPES,
    phases: NO_DELOAD,
    default_sets: 1,
    default_reps: '6×60m',
    default_rest_seconds: 90,
    default_rpe: 8,
    coaching_cues: ['Build into top speed over the first 20m', 'Stay relaxed through the shoulders', 'Full recovery between reps'],
    is_compound: false,
    conditioning_type: 'sprint',
    movement_pattern: 'conditioning',
    min_experience: 'intermediate',
  },
  {
    name: 'VO2 Max Intervals 4×4min',
    category: 'vo2max',
    equipment: ALL_EQUIPMENT,
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 1,
    default_reps: '4×4min',
    default_rest_seconds: 180,
    default_rpe: 8,
    coaching_cues: ['Hold a hard but sustainable effort', 'Use the rest to fully recover your breathing', 'Pace evenly across intervals'],
    is_compound: false,
    conditioning_type: 'interval',
    movement_pattern: 'conditioning',
    min_experience: 'advanced',
  },
  {
    name: 'VO2 Max Intervals 5×3min',
    category: 'vo2max',
    equipment: ALL_EQUIPMENT,
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 1,
    default_reps: '5×3min',
    default_rest_seconds: 120,
    default_rpe: 8,
    coaching_cues: ['Settle into rhythm by 30 seconds', 'Keep effort consistent across reps', 'Breathe through the recovery'],
    is_compound: false,
    conditioning_type: 'interval',
    movement_pattern: 'conditioning',
  },
  {
    name: 'Hill Sprint Repeats 8×15s',
    category: 'sprint',
    equipment: ALL_EQUIPMENT,
    archetypes: ALL_ARCHETYPES,
    phases: NO_DELOAD,
    default_sets: 1,
    default_reps: '8×15s',
    default_rest_seconds: 90,
    default_rpe: 8,
    coaching_cues: ['Drive knees high up the hill', 'Walk back down for full recovery', 'Keep effort maximal but controlled'],
    is_compound: false,
    conditioning_type: 'sprint',
    movement_pattern: 'conditioning',
    min_experience: 'advanced',
  },
  {
    name: 'Assault Bike Tabata 8×20s',
    category: 'conditioning',
    equipment: ['full_gym', 'home_gym'],
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 1,
    default_reps: '8×20s',
    default_rest_seconds: 10,
    default_rpe: 9,
    coaching_cues: ['All-out effort for the full 20 seconds', 'Use the 10 second rest to reset posture', 'Pace to maintain output across all rounds'],
    home_alternative: 'Burpee Tabata 8×20s',
    is_compound: false,
    conditioning_type: 'tabata',
    movement_pattern: 'conditioning',
    min_experience: 'advanced',
  },
  {
    name: 'Run Zone 2 30min',
    category: 'conditioning',
    equipment: ALL_EQUIPMENT,
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 1,
    default_reps: '30min',
    default_rest_seconds: 0,
    default_rpe: 5,
    coaching_cues: ['Conversational pace throughout', 'Nasal breathing if possible', 'Resist the urge to speed up'],
    is_compound: false,
    conditioning_type: 'steady_state',
    movement_pattern: 'conditioning',
  },
  {
    name: 'Run Zone 2 40min',
    category: 'conditioning',
    equipment: ALL_EQUIPMENT,
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 1,
    default_reps: '40min',
    default_rest_seconds: 0,
    default_rpe: 5,
    coaching_cues: ['Hold an easy, sustainable pace', 'Stay relaxed through the shoulders and jaw', 'Fuel before if over 60 minutes'],
    is_compound: false,
    conditioning_type: 'steady_state',
    movement_pattern: 'conditioning',
  },
  {
    name: 'Tempo Run 20min',
    category: 'conditioning',
    equipment: ALL_EQUIPMENT,
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 1,
    default_reps: '20min',
    default_rest_seconds: 0,
    default_rpe: 7,
    coaching_cues: ['Comfortably hard, sustainable effort', 'Settle in gradually over the first 5 minutes', 'Hold form as fatigue builds'],
    is_compound: false,
    conditioning_type: 'steady_state',
    movement_pattern: 'conditioning',
  },
  {
    name: 'Tempo Run 25min',
    category: 'conditioning',
    equipment: ALL_EQUIPMENT,
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 1,
    default_reps: '25min',
    default_rest_seconds: 0,
    default_rpe: 7,
    coaching_cues: ['Lock into a rhythm you can repeat', 'Effort should feel hard but controlled', 'Negative split if you feel strong'],
    is_compound: false,
    conditioning_type: 'steady_state',
    movement_pattern: 'conditioning',
  },
  {
    name: 'Interval Run 6×800m',
    category: 'vo2max',
    equipment: ALL_EQUIPMENT,
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 1,
    default_reps: '6×800m',
    default_rest_seconds: 120,
    default_rpe: 8,
    coaching_cues: ['Even pacing across all reps', 'Use the recovery jog to reset form', 'Last rep should feel as strong as the first'],
    is_compound: false,
    conditioning_type: 'interval',
    movement_pattern: 'conditioning',
  },
  {
    name: 'Interval Run 8×400m',
    category: 'vo2max',
    equipment: ALL_EQUIPMENT,
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 1,
    default_reps: '8×400m',
    default_rest_seconds: 90,
    default_rpe: 8,
    coaching_cues: ['Hit your target split each rep', 'Recover with an easy jog or walk', 'Stay relaxed at speed'],
    is_compound: false,
    conditioning_type: 'interval',
    movement_pattern: 'conditioning',
  },
  {
    name: 'Long Run 45min',
    category: 'conditioning',
    equipment: ALL_EQUIPMENT,
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 1,
    default_reps: '45min',
    default_rest_seconds: 0,
    default_rpe: 6,
    coaching_cues: ['Start conservatively', 'Practice race-day fuelling', 'Slow down rather than skip the distance'],
    is_compound: false,
    conditioning_type: 'steady_state',
    movement_pattern: 'conditioning',
  },
  {
    name: 'Long Run 60min+',
    category: 'conditioning',
    equipment: ALL_EQUIPMENT,
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 1,
    default_reps: '60min',
    default_rest_seconds: 0,
    default_rpe: 6,
    coaching_cues: ['Build distance gradually week to week', 'Fuel and hydrate on schedule', 'Finish feeling like you had more in reserve'],
    is_compound: false,
    conditioning_type: 'steady_state',
    movement_pattern: 'conditioning',
  },

  // ───────────── AGILITY ─────────────
  {
    name: 'Lateral Shuffle 4×10m',
    category: 'lateral',
    equipment: ALL_EQUIPMENT,
    archetypes: ['Athletic Performance', 'Hybrid Performer'],
    phases: NO_DELOAD,
    default_sets: 1,
    default_reps: '4×10m',
    default_rest_seconds: 45,
    default_rpe: 6,
    coaching_cues: ['Stay low with bent knees', 'Quick, light feet', 'Lead with the hips, not the head'],
    is_compound: false,
    movement_pattern: 'other',
  },
  {
    name: '5-10-5 Agility Drill',
    category: 'agility',
    equipment: ALL_EQUIPMENT,
    archetypes: ['Athletic Performance', 'Hybrid Performer'],
    phases: NO_DELOAD,
    default_sets: 1,
    default_reps: '5x',
    default_rest_seconds: 60,
    default_rpe: 7,
    coaching_cues: ['Plant and drive out of each cut', 'Stay low through direction changes', 'Full recovery between reps'],
    is_compound: false,
    movement_pattern: 'other',
    min_experience: 'intermediate',
  },
  {
    name: 'T-Drill',
    category: 'agility',
    equipment: ALL_EQUIPMENT,
    archetypes: ['Athletic Performance', 'Hybrid Performer'],
    phases: NO_DELOAD,
    default_sets: 1,
    default_reps: '5x',
    default_rest_seconds: 60,
    default_rpe: 7,
    coaching_cues: ['Sprint forward, shuffle laterally, backpedal', 'Keep hips low on the shuffles', 'Quality over speed early on'],
    is_compound: false,
    movement_pattern: 'other',
    min_experience: 'intermediate',
  },
  {
    name: 'Cone Drill',
    category: 'agility',
    equipment: ALL_EQUIPMENT,
    archetypes: ['Athletic Performance', 'Hybrid Performer'],
    phases: NO_DELOAD,
    default_sets: 1,
    default_reps: '5x',
    default_rest_seconds: 60,
    default_rpe: 6,
    coaching_cues: ['Sharp, controlled cuts around each cone', 'Keep your centre of gravity low', 'Accelerate out of every turn'],
    is_compound: false,
    movement_pattern: 'other',
  },
  {
    name: 'Agility Ladder High Knees',
    category: 'agility',
    equipment: ALL_EQUIPMENT,
    archetypes: ['Athletic Performance', 'Hybrid Performer'],
    phases: NO_DELOAD,
    default_sets: 1,
    default_reps: '4x',
    default_rest_seconds: 45,
    default_rpe: 6,
    coaching_cues: ['One foot in each box', 'Drive knees up quickly', 'Stay light on your feet'],
    is_compound: false,
    movement_pattern: 'other',
  },
  {
    name: 'Reactive Drop Step',
    category: 'agility',
    equipment: ALL_EQUIPMENT,
    archetypes: ['Athletic Performance', 'Hybrid Performer'],
    phases: NO_DELOAD,
    default_sets: 1,
    default_reps: '4x',
    default_rest_seconds: 45,
    default_rpe: 6,
    coaching_cues: ['React to the cue as fast as possible', 'Drop step and accelerate explosively', 'Reset athletic stance between reps'],
    is_compound: false,
    movement_pattern: 'other',
    min_experience: 'advanced',
  },

  // ───────────── CORE / ANTI-ROTATION ─────────────
  {
    name: 'Cable Pallof Press',
    category: 'core',
    equipment: ['full_gym'],
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: 12,
    default_rest_seconds: 45,
    default_rpe: 6,
    coaching_cues: ['Resist rotation toward the cable', 'Press out slowly and with control', 'Keep ribs stacked over hips'],
    home_alternative: 'Band Pallof Press',
    is_compound: false,
    movement_pattern: 'core',
  },
  {
    name: 'Dead Bug',
    category: 'core',
    equipment: ALL_EQUIPMENT,
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: 10,
    default_rest_seconds: 30,
    default_rpe: 5,
    coaching_cues: ['Press lower back into the floor', 'Move opposite arm and leg slowly', 'Exhale fully on each rep'],
    is_compound: false,
    movement_pattern: 'core',
  },
  {
    name: 'Copenhagen Plank',
    category: 'core',
    equipment: ALL_EQUIPMENT,
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: '30s',
    default_rest_seconds: 45,
    default_rpe: 6,
    coaching_cues: ['Top leg on the bench, bottom leg lifted', 'Keep hips square and lifted', 'Build time gradually'],
    is_compound: false,
    movement_pattern: 'core',
  },
  {
    name: 'Plank',
    category: 'core',
    equipment: ALL_EQUIPMENT,
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: '45s',
    default_rest_seconds: 30,
    default_rpe: 5,
    coaching_cues: ['Squeeze glutes and brace your core', 'Keep a straight line head to heels', 'Breathe steadily throughout'],
    is_compound: false,
    movement_pattern: 'core',
  },
  {
    name: 'Side Plank',
    category: 'core',
    equipment: ALL_EQUIPMENT,
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: '30s each side',
    default_rest_seconds: 30,
    default_rpe: 5,
    coaching_cues: ['Stack hips and shoulders', 'Lift hips as high as comfortable', 'Keep neck neutral'],
    is_compound: false,
    movement_pattern: 'core',
  },
  {
    name: 'Ab Wheel Rollout',
    category: 'core',
    equipment: ['full_gym', 'home_gym'],
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: 8,
    default_rest_seconds: 60,
    default_rpe: 6,
    coaching_cues: ['Brace before you roll out', 'Roll only as far as you can control', 'Pull back using your abs, not your hips'],
    is_compound: false,
    movement_pattern: 'core',
  },

  // ───────────── ISOLATION ─────────────
  {
    name: 'Bicep Curl',
    category: 'upper_pull',
    equipment: ['full_gym', 'home_gym'],
    archetypes: ['Bodybuilder', 'General Fitness', 'Strength Athlete'],
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: 12,
    default_rest_seconds: 45,
    default_rpe: 6,
    coaching_cues: ['Keep elbows pinned to your sides', 'Control the lowering phase', 'Avoid swinging the weight'],
    is_compound: false,
    // Isolation arm work, not a primary pull pattern — never competes for a
    // blueprint pull_horizontal/pull_vertical main_lift slot.
    movement_pattern: 'pull_accessory',
  },
  {
    name: 'Tricep Pushdown',
    category: 'upper_push',
    equipment: ['full_gym', 'home_gym'],
    archetypes: ['Bodybuilder', 'General Fitness', 'Strength Athlete'],
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: 12,
    default_rest_seconds: 45,
    default_rpe: 6,
    coaching_cues: ['Keep elbows fixed at your sides', 'Extend fully without locking out hard', 'Control the return'],
    is_compound: false,
    // Isolation triceps work, not a primary push pattern — no push_accessory
    // bucket exists, so this never competes for a blueprint main_lift slot.
    movement_pattern: 'other',
  },
  {
    name: 'Lateral Raise',
    category: 'upper_push',
    equipment: ['full_gym', 'home_gym'],
    archetypes: ['Bodybuilder', 'General Fitness', 'Strength Athlete'],
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: 15,
    default_rest_seconds: 45,
    default_rpe: 6,
    coaching_cues: ['Lead with the elbows', 'Raise to shoulder height', 'Avoid using momentum'],
    is_compound: false,
    movement_pattern: 'other',
  },
  {
    name: 'Face Pull',
    category: 'upper_pull',
    equipment: ['full_gym', 'home_gym'],
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: 15,
    default_rest_seconds: 45,
    default_rpe: 5,
    coaching_cues: ['Pull to your forehead', 'Rotate shoulders externally at the end', 'Keep elbows high'],
    is_compound: false,
    movement_pattern: 'pull_accessory',
  },
  {
    name: 'Leg Curl',
    category: 'lower',
    equipment: ['full_gym'],
    archetypes: ['Bodybuilder', 'General Fitness', 'Strength Athlete'],
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: 12,
    default_rest_seconds: 60,
    default_rpe: 6,
    coaching_cues: ['Control the eccentric', 'Squeeze hamstrings at the top', 'Avoid hips lifting off the pad'],
    is_compound: false,
    movement_pattern: 'hinge',
  },
  {
    name: 'Leg Extension',
    category: 'lower',
    equipment: ['full_gym'],
    archetypes: ['Bodybuilder', 'General Fitness', 'Strength Athlete'],
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: 12,
    default_rest_seconds: 60,
    default_rpe: 6,
    coaching_cues: ['Control the weight on the way down', 'Squeeze quads at the top', 'Avoid locking out aggressively'],
    is_compound: false,
    movement_pattern: 'squat',
  },
  {
    name: 'Calf Raise',
    category: 'lower',
    equipment: ALL_EQUIPMENT,
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: 15,
    default_rest_seconds: 45,
    default_rpe: 6,
    coaching_cues: ['Full stretch at the bottom', 'Pause at the top of each rep', 'Control the tempo'],
    is_compound: false,
    movement_pattern: 'other',
  },
  {
    name: 'Glute Kickback',
    category: 'lower',
    equipment: ['full_gym', 'home_gym', 'bodyweight'],
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: 15,
    default_rest_seconds: 45,
    default_rpe: 6,
    coaching_cues: ['Squeeze the glute at the top', 'Avoid arching your lower back', 'Move through a controlled range'],
    is_compound: false,
    movement_pattern: 'hinge',
  },

  // ───────────── MOBILITY / WARM-UP ─────────────
  {
    name: "World's Greatest Stretch",
    category: 'mobility',
    equipment: ALL_EQUIPMENT,
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 1,
    default_reps: '5 each side',
    default_rest_seconds: 0,
    default_rpe: 4,
    coaching_cues: ['Move through the full range slowly', 'Breathe into each position', 'Sink deeper each rep'],
    is_compound: false,
    movement_pattern: 'other',
  },
  {
    name: 'Hip 90/90',
    category: 'mobility',
    equipment: ALL_EQUIPMENT,
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 1,
    default_reps: '8 each side',
    default_rest_seconds: 0,
    default_rpe: 4,
    coaching_cues: ['Keep both sit bones on the floor', 'Rotate from the hip, not the back', 'Move slowly and with control'],
    is_compound: false,
    movement_pattern: 'other',
  },
  {
    name: 'Thoracic Rotation',
    category: 'mobility',
    equipment: ALL_EQUIPMENT,
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 1,
    default_reps: 10,
    default_rest_seconds: 0,
    default_rpe: 4,
    coaching_cues: ['Keep hips stacked and still', 'Rotate through the upper back', 'Follow your hand with your eyes'],
    is_compound: false,
    movement_pattern: 'other',
  },
  {
    name: 'Band Pull-Apart',
    category: 'mobility',
    equipment: ['full_gym', 'home_gym'],
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 2,
    default_reps: 15,
    default_rest_seconds: 0,
    default_rpe: 4,
    coaching_cues: ['Squeeze shoulder blades together', 'Keep arms straight', 'Control the return'],
    home_alternative: 'Arm circles',
    is_compound: false,
    movement_pattern: 'pull_accessory',
  },
  {
    name: 'Leg Swing',
    category: 'mobility',
    equipment: ALL_EQUIPMENT,
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 1,
    default_reps: '10 each leg',
    default_rest_seconds: 0,
    default_rpe: 4,
    coaching_cues: ['Hold something stable for balance', 'Swing through a comfortable range', 'Increase range gradually'],
    is_compound: false,
    movement_pattern: 'other',
  },
  {
    name: 'Arm Circle',
    category: 'mobility',
    equipment: ALL_EQUIPMENT,
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 1,
    default_reps: 10,
    default_rest_seconds: 0,
    default_rpe: 3,
    coaching_cues: ['Start small and increase the size', 'Keep arms long', 'Both directions'],
    is_compound: false,
    movement_pattern: 'other',
  },
  {
    name: 'Inchworm',
    category: 'mobility',
    equipment: ALL_EQUIPMENT,
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 1,
    default_reps: 8,
    default_rest_seconds: 0,
    default_rpe: 5,
    coaching_cues: ['Walk hands out to a plank', 'Keep legs as straight as comfortable', 'Walk feet up to meet hands'],
    is_compound: false,
    movement_pattern: 'other',
  },
  {
    name: 'Cat-Cow',
    category: 'mobility',
    equipment: ALL_EQUIPMENT,
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 1,
    default_reps: 10,
    default_rest_seconds: 0,
    default_rpe: 3,
    coaching_cues: ['Move slowly between each position', 'Match breath to movement', 'Feel the stretch through your spine'],
    is_compound: false,
    movement_pattern: 'other',
  },
  {
    name: 'Hip Circle',
    category: 'mobility',
    equipment: ALL_EQUIPMENT,
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 1,
    default_reps: '8 each direction',
    default_rest_seconds: 0,
    default_rpe: 4,
    coaching_cues: ['Keep your standing leg stable', 'Move through the largest comfortable circle', 'Both directions, both legs'],
    is_compound: false,
    movement_pattern: 'other',
  },

  // ───────────── CYCLING ─────────────
  {
    name: 'Bike Zone 2 45min',
    category: 'conditioning',
    equipment: ['full_gym', 'home_gym'],
    archetypes: ['Endurance Athlete'],
    phases: ALL_PHASES,
    default_sets: 1,
    default_reps: '45min',
    default_rest_seconds: 0,
    default_rpe: 5,
    coaching_cues: ['Hold a conversational effort', 'Maintain a smooth, even cadence', 'Resist the urge to push the pace'],
    is_compound: false,
    conditioning_type: 'steady_state',
    movement_pattern: 'conditioning',
  },
  {
    name: 'Bike Intervals 6×3min',
    category: 'vo2max',
    equipment: ['full_gym', 'home_gym'],
    archetypes: ['Endurance Athlete'],
    phases: ALL_PHASES,
    default_sets: 1,
    default_reps: '6×3min',
    default_rest_seconds: 120,
    default_rpe: 8,
    coaching_cues: ['Build effort over the first 30 seconds', 'Hold cadence consistent across reps', 'Recover fully between intervals'],
    is_compound: false,
    conditioning_type: 'interval',
    movement_pattern: 'conditioning',
  },
  {
    name: 'Recovery Ride 30min',
    category: 'conditioning',
    equipment: ['full_gym', 'home_gym'],
    archetypes: ['Endurance Athlete'],
    phases: ALL_PHASES,
    default_sets: 1,
    default_reps: '30min',
    default_rest_seconds: 0,
    default_rpe: 4,
    coaching_cues: ['Very light effort, easy gear', 'Focus on smooth pedalling', 'This is active recovery, not training'],
    is_compound: false,
    conditioning_type: 'steady_state',
    movement_pattern: 'conditioning',
  },
  {
    name: 'Long Ride 60min',
    category: 'conditioning',
    equipment: ['full_gym', 'home_gym'],
    archetypes: ['Endurance Athlete'],
    phases: ALL_PHASES,
    default_sets: 1,
    default_reps: '60min',
    default_rest_seconds: 0,
    default_rpe: 6,
    coaching_cues: ['Settle into a sustainable rhythm', 'Practice your nutrition strategy', 'Build duration gradually week to week'],
    is_compound: false,
    conditioning_type: 'steady_state',
    movement_pattern: 'conditioning',
  },
  {
    name: 'Brick Session Bike 20min + Run 15min',
    category: 'conditioning',
    equipment: ['full_gym', 'home_gym'],
    archetypes: ['Endurance Athlete'],
    phases: ALL_PHASES,
    default_sets: 1,
    default_reps: '20min+15min',
    default_rest_seconds: 0,
    default_rpe: 7,
    coaching_cues: ['Transition quickly from bike to run', 'Expect heavy legs in the first few minutes of the run', 'Hold an even effort across both'],
    is_compound: false,
    conditioning_type: 'steady_state',
    movement_pattern: 'conditioning',
  },

  // ───────────── HYROX ─────────────
  {
    name: 'Ski Erg Intervals 6×250m',
    category: 'conditioning',
    equipment: ['full_gym'],
    archetypes: ['HYROX Competitor'],
    phases: ALL_PHASES,
    default_sets: 1,
    default_reps: '6×250m',
    default_rest_seconds: 60,
    default_rpe: 8,
    coaching_cues: ['Drive through your legs first', 'Maintain a strong hip hinge', 'Pace evenly across all reps'],
    is_compound: false,
    conditioning_type: 'interval',
    is_hyrox_station: true,
    movement_pattern: 'conditioning',
  },
  {
    name: 'Wall Ball 4×25 reps',
    category: 'conditioning',
    equipment: ['full_gym', 'home_gym'],
    archetypes: ['HYROX Competitor'],
    phases: ALL_PHASES,
    default_sets: 4,
    default_reps: 25,
    default_rest_seconds: 60,
    default_rpe: 7,
    coaching_cues: ['Squat to full depth each rep', 'Use leg drive to throw the ball', 'Catch and absorb into the next squat'],
    is_compound: false,
    conditioning_type: 'circuit',
    is_hyrox_station: true,
    movement_pattern: 'conditioning',
  },
  {
    name: 'Farmers Carry 4×50m',
    category: 'loaded_carry',
    equipment: ['full_gym', 'home_gym'],
    archetypes: ['HYROX Competitor'],
    phases: ALL_PHASES,
    default_sets: 4,
    default_reps: '50m',
    default_rest_seconds: 60,
    default_rpe: 7,
    coaching_cues: ['Grip the handles tight', 'Stand tall, controlled stride', 'Set down with control between attempts'],
    is_compound: false,
    is_hyrox_station: true,
    movement_pattern: 'carry',
  },
  {
    name: 'Burpee Broad Jump 3×10',
    category: 'power',
    equipment: ALL_EQUIPMENT,
    archetypes: ['HYROX Competitor'],
    phases: NO_DELOAD,
    default_sets: 3,
    default_reps: 10,
    default_rest_seconds: 60,
    default_rpe: 8,
    coaching_cues: ['Chest to the floor on the burpee', 'Explode forward into the broad jump', 'Reset stance before the next rep'],
    is_compound: false,
    is_hyrox_station: true,
    movement_pattern: 'other',
  },
  {
    name: 'Sandbag Lunges 3×20m',
    category: 'lower',
    equipment: ['full_gym', 'home_gym'],
    archetypes: ['HYROX Competitor'],
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: '20m',
    default_rest_seconds: 60,
    default_rpe: 7,
    coaching_cues: ['Keep the sandbag tight to your body', 'Drive through the front heel', 'Maintain an upright torso'],
    is_compound: false,
    is_hyrox_station: true,
    movement_pattern: 'carry',
  },
  {
    name: 'Rowing 1000m Repeats ×4',
    category: 'conditioning',
    equipment: ['full_gym'],
    archetypes: ['HYROX Competitor'],
    phases: ALL_PHASES,
    default_sets: 1,
    default_reps: '4×1000m',
    default_rest_seconds: 120,
    default_rpe: 8,
    coaching_cues: ['Drive with the legs before the arms', 'Keep the stroke rate consistent', 'Even pacing across all reps'],
    is_compound: false,
    conditioning_type: 'interval',
    is_hyrox_station: true,
    movement_pattern: 'conditioning',
  },

  // ───────────── HYROX STATIONS ─────────────
  {
    name: 'SkiErg Endurance 1000m',
    category: 'conditioning',
    equipment: ['full_gym'],
    archetypes: ['HYROX Competitor'],
    phases: ['peak'],
    default_sets: 1,
    default_reps: '1000m',
    default_rest_seconds: 0,
    default_rpe: 8,
    coaching_cues: ['Race-distance effort', 'Practice pacing — don\'t go out too hot', 'Drive through legs and core, not just arms'],
    is_compound: false,
    conditioning_type: 'steady_state',
    is_hyrox_station: true,
    movement_pattern: 'conditioning',
  },
  {
    name: 'Sled Push 6×25m',
    category: 'loaded_carry',
    equipment: ['full_gym'],
    archetypes: ['HYROX Competitor'],
    phases: ['build', 'peak'],
    default_sets: 6,
    default_reps: '25m',
    default_rest_seconds: 60,
    default_rpe: 8,
    coaching_cues: ['Low body position, drive through the floor', 'This is the HYROX competition distance', 'Practice the exact movement pattern'],
    home_alternative: 'Load a sturdy bag on a smooth floor, push for 10m with max effort',
    is_compound: true,
    is_hyrox_station: true,
    movement_pattern: 'carry',
    min_experience: 'intermediate',
  },
  {
    name: 'Sled Pull 6×25m',
    category: 'loaded_carry',
    equipment: ['full_gym'],
    archetypes: ['HYROX Competitor'],
    phases: ['build', 'peak'],
    default_sets: 6,
    default_reps: '25m',
    default_rest_seconds: 60,
    default_rpe: 8,
    coaching_cues: ['Lean back, pull through hips and legs not just arms', 'Competition distance — practice the pattern', 'Control foot placement on the rope pull'],
    home_alternative: 'Resistance band anchored at waist height, drive forward against resistance for 10m',
    is_compound: true,
    is_hyrox_station: true,
    movement_pattern: 'carry',
    min_experience: 'intermediate',
  },
  {
    name: 'Burpee Broad Jump 4×10',
    category: 'plyometric',
    equipment: ALL_EQUIPMENT,
    archetypes: ['HYROX Competitor'],
    phases: ['build', 'peak'],
    default_sets: 4,
    default_reps: 10,
    default_rest_seconds: 60,
    default_rpe: 8,
    coaching_cues: ['Full burpee, then maximum broad jump', 'Competition pacing means finding a sustainable rhythm', 'Don\'t sprint the first 20 reps'],
    is_compound: false,
    is_hyrox_station: true,
    movement_pattern: 'other',
  },
  {
    name: 'Rowing Endurance 1000m',
    category: 'conditioning',
    equipment: ['full_gym'],
    archetypes: ['HYROX Competitor'],
    phases: ['peak'],
    default_sets: 1,
    default_reps: '1000m',
    default_rest_seconds: 0,
    default_rpe: 8,
    coaching_cues: ['Drive with legs first then arms', 'Competition distance, race-pace effort', 'Consistent stroke rate throughout'],
    is_compound: false,
    conditioning_type: 'steady_state',
    is_hyrox_station: true,
    movement_pattern: 'conditioning',
  },
  {
    name: 'Farmers Carry HYROX 4×50m',
    category: 'loaded_carry',
    equipment: ['full_gym', 'home_gym'],
    archetypes: ['HYROX Competitor'],
    phases: ['build', 'peak'],
    default_sets: 4,
    default_reps: '50m',
    default_rest_seconds: 60,
    default_rpe: 7,
    coaching_cues: ['Tall spine, shoulders packed', 'Grip will fatigue before your legs do — train grip endurance', 'Competition distance build-up'],
    home_alternative: 'Heaviest dumbbells or filled bags available',
    is_compound: false,
    is_hyrox_station: true,
    movement_pattern: 'carry',
  },
  {
    name: 'Sandbag Lunges HYROX 4×25m',
    category: 'lower',
    equipment: ['full_gym', 'home_gym'],
    archetypes: ['HYROX Competitor'],
    phases: ['build', 'peak'],
    default_sets: 4,
    default_reps: '25m',
    default_rest_seconds: 60,
    default_rpe: 7,
    coaching_cues: ['Sandbag on shoulders, controlled walking lunges', 'Competition is 100m total — build toward unbroken sets', 'Drive through the front heel'],
    is_compound: false,
    is_hyrox_station: true,
    movement_pattern: 'carry',
  },
  {
    name: 'Wall Balls Competition Volume 75 reps',
    category: 'conditioning',
    equipment: ['full_gym'],
    archetypes: ['HYROX Competitor'],
    phases: ['peak'],
    default_sets: 1,
    default_reps: '75 reps',
    default_rest_seconds: 0,
    default_rpe: 8,
    coaching_cues: ['Full competition rep count in one session', 'Break into manageable sets with short rests', 'Peak-phase test — squat to full depth every rep'],
    is_compound: false,
    conditioning_type: 'circuit',
    is_hyrox_station: true,
    movement_pattern: 'conditioning',
  },

  // ───────────── UPPER PUSH ADDITIONS ─────────────
  {
    name: 'Dumbbell Bench Press',
    category: 'upper_push',
    equipment: ['full_gym', 'home_gym'],
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: 10,
    default_rest_seconds: 90,
    default_rpe: 7,
    coaching_cues: ['Control the descent', 'Press to full lockout', 'Neutral wrist throughout'],
    is_compound: true,
    movement_pattern: 'push_horizontal',
  },
  {
    name: 'Incline Dumbbell Press',
    category: 'upper_push',
    equipment: ['full_gym', 'home_gym'],
    archetypes: ['Bodybuilder', 'Strength Athlete', 'General Fitness', 'Hybrid Performer', 'Athletic Performance'],
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: 10,
    default_rest_seconds: 90,
    default_rpe: 7,
    coaching_cues: ['30-45 degree incline', 'Slight arc on the press', 'Avoid flaring elbows'],
    is_compound: true,
    movement_pattern: 'push_horizontal',
    min_experience: 'intermediate',
  },
  {
    name: 'Pike Push-Up',
    category: 'upper_push',
    equipment: ALL_EQUIPMENT,
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: 8,
    default_rest_seconds: 60,
    default_rpe: 7,
    coaching_cues: ['Hips high, inverted V shape', 'Lower head toward floor', 'Press back to start'],
    is_compound: false,
    movement_pattern: 'push_vertical',
  },
  {
    name: 'Dumbbell Overhead Press',
    category: 'upper_push',
    equipment: ['full_gym', 'home_gym'],
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: 10,
    default_rest_seconds: 90,
    default_rpe: 7,
    coaching_cues: ['Press directly overhead', 'Avoid excessive arch', 'Control the descent'],
    is_compound: true,
    movement_pattern: 'push_vertical',
  },
  {
    name: 'Cable Chest Fly',
    category: 'upper_push',
    equipment: ['full_gym'],
    archetypes: ['Bodybuilder', 'General Fitness', 'Fat Loss', 'Functional Strength & Conditioning'],
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: 12,
    default_rest_seconds: 60,
    default_rpe: 7,
    coaching_cues: ['Slight bend in elbow throughout', 'Feel the stretch at the bottom', 'Squeeze at the top'],
    is_compound: false,
    movement_pattern: 'push_horizontal',
  },
  {
    name: 'Landmine Press',
    category: 'upper_push',
    equipment: ['full_gym'],
    archetypes: ['Athletic Performance', 'Hybrid Performer', 'Functional Strength & Conditioning', 'Strength Athlete'],
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: 8,
    default_rest_seconds: 90,
    default_rpe: 7,
    coaching_cues: ['Single arm, staggered stance', 'Drive from the hip', 'Full lockout at the top'],
    is_compound: true,
    movement_pattern: 'push_vertical',
    min_experience: 'intermediate',
  },

  // ───────────── UPPER PULL ADDITIONS ─────────────
  {
    name: 'Lat Pulldown',
    category: 'upper_pull',
    equipment: ['full_gym'],
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: 10,
    default_rest_seconds: 90,
    default_rpe: 7,
    coaching_cues: ['Lean back slightly', 'Pull to upper chest', 'Control the return'],
    is_compound: true,
    movement_pattern: 'pull_vertical',
  },
  {
    name: 'Seated Cable Row',
    category: 'upper_pull',
    equipment: ['full_gym'],
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: 10,
    default_rest_seconds: 90,
    default_rpe: 7,
    coaching_cues: ['Drive elbows back', 'Squeeze shoulder blades', 'Avoid rounding forward'],
    is_compound: true,
    movement_pattern: 'pull_horizontal',
  },
  {
    name: 'Dumbbell Row',
    category: 'upper_pull',
    equipment: ['full_gym', 'home_gym'],
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: 10,
    default_rest_seconds: 60,
    default_rpe: 7,
    coaching_cues: ['Brace on the bench', 'Elbow close to body', 'Full stretch at the bottom'],
    is_compound: false,
    movement_pattern: 'pull_horizontal',
  },
  {
    name: 'Inverted Row',
    category: 'upper_pull',
    equipment: ['full_gym', 'home_gym'],
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: 10,
    default_rest_seconds: 60,
    default_rpe: 7,
    coaching_cues: ['Body straight like a plank', 'Pull chest to bar', 'Easier = raise bar, harder = lower it'],
    is_compound: true,
    movement_pattern: 'pull_horizontal',
  },
  {
    name: 'Cable Face Pull',
    category: 'upper_pull',
    equipment: ['full_gym'],
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: 15,
    default_rest_seconds: 45,
    default_rpe: 6,
    coaching_cues: ['Pull to face height', 'External rotate at the top', 'Light weight, feel the rear delt'],
    is_compound: false,
    movement_pattern: 'pull_accessory',
  },
  {
    name: 'Chest-Supported Row',
    category: 'upper_pull',
    equipment: ['full_gym'],
    archetypes: ['Bodybuilder', 'Strength Athlete', 'General Fitness', 'Athletic Performance'],
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: 10,
    default_rest_seconds: 90,
    default_rpe: 7,
    coaching_cues: ['Chest on pad removes lower back', 'Full range of motion', 'Squeeze at the top'],
    is_compound: true,
    movement_pattern: 'pull_horizontal',
  },
  {
    name: 'Single Arm Lat Pulldown',
    category: 'upper_pull',
    equipment: ['full_gym'],
    archetypes: ['Bodybuilder', 'General Fitness', 'Athletic Performance', 'Functional Strength & Conditioning'],
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: 12,
    default_rest_seconds: 60,
    default_rpe: 7,
    coaching_cues: ['Control rotation', 'Full stretch at top', 'Drive elbow to hip'],
    is_compound: false,
    movement_pattern: 'pull_vertical',
  },
  {
    name: 'Meadows Row',
    category: 'upper_pull',
    equipment: ['full_gym'],
    archetypes: ['Bodybuilder', 'Strength Athlete', 'Athletic Performance'],
    phases: NO_DELOAD,
    default_sets: 3,
    default_reps: 8,
    default_rest_seconds: 90,
    default_rpe: 8,
    coaching_cues: ['Landmine setup, perpendicular stance', 'Drive elbow high and wide', 'Massive stretch at bottom'],
    is_compound: true,
    movement_pattern: 'pull_horizontal',
    min_experience: 'advanced',
  },

  // ───────────── LOWER BODY ADDITIONS ─────────────
  {
    name: 'Bodyweight Squat',
    category: 'lower',
    equipment: ALL_EQUIPMENT,
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: 15,
    default_rest_seconds: 45,
    default_rpe: 5,
    coaching_cues: ['Feet shoulder-width', 'Knees track over toes', 'Chest up throughout'],
    is_compound: true,
    movement_pattern: 'squat',
  },
  {
    name: 'Step-Up',
    category: 'lower',
    equipment: ['full_gym', 'home_gym'],
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: 10,
    default_rest_seconds: 60,
    default_rpe: 6,
    coaching_cues: ['Drive through the heel on the box', 'Control the descent', 'Alternate legs or complete one side'],
    is_compound: true,
    movement_pattern: 'squat',
  },
  {
    name: 'Glute Bridge',
    category: 'lower',
    equipment: ALL_EQUIPMENT,
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: 15,
    default_rest_seconds: 45,
    default_rpe: 5,
    coaching_cues: ['Drive hips to ceiling', 'Squeeze glutes at top', 'Feet flat, knees at 90 degrees'],
    is_compound: false,
    movement_pattern: 'hinge',
  },
  {
    name: 'Nordic Hamstring Curl',
    category: 'lower',
    equipment: ['full_gym'],
    archetypes: ['Athletic Performance', 'Hybrid Performer', 'Strength Athlete', 'Functional Strength & Conditioning'],
    phases: NO_DELOAD,
    default_sets: 3,
    default_reps: 5,
    default_rest_seconds: 120,
    default_rpe: 8,
    coaching_cues: ['Anchor feet firmly', 'Lower under control — this is the work', 'Use hands to push up if needed'],
    is_compound: false,
    movement_pattern: 'hinge',
    min_experience: 'intermediate',
  },
  {
    name: 'Single Leg Romanian Deadlift',
    category: 'lower',
    equipment: ['full_gym', 'home_gym'],
    archetypes: ['Athletic Performance', 'Hybrid Performer', 'General Fitness', 'Functional Strength & Conditioning'],
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: 8,
    default_rest_seconds: 60,
    default_rpe: 7,
    coaching_cues: ['Hip hinge, not a squat', 'Keep hips level throughout', 'Soft knee on the standing leg'],
    is_compound: true,
    movement_pattern: 'hinge',
    min_experience: 'intermediate',
  },
  {
    name: 'Wall Sit',
    category: 'lower',
    equipment: ALL_EQUIPMENT,
    archetypes: ALL_ARCHETYPES,
    phases: ALL_PHASES,
    default_sets: 3,
    default_reps: '30s',
    default_rest_seconds: 60,
    default_rpe: 6,
    coaching_cues: ['90 degree knee angle', 'Back flat against wall', 'Drive through heels'],
    is_compound: false,
    movement_pattern: 'squat',
  },

  // ───────────── ENDURANCE / EVENT-SPECIFIC ADDITIONS ─────────────
  {
    name: 'Strides 6×100m',
    category: 'conditioning',
    equipment: ALL_EQUIPMENT,
    archetypes: ['Endurance Athlete'],
    phases: ALL_PHASES,
    default_sets: 1,
    default_reps: '6×100m',
    default_rest_seconds: 60,
    default_rpe: 7,
    coaching_cues: ['Controlled acceleration to 90% effort', 'Focus on form not speed', 'Full recovery between each'],
    is_compound: false,
    conditioning_type: 'interval',
    movement_pattern: 'conditioning',
  },
  {
    name: 'Fartlek Run 30min',
    category: 'conditioning',
    equipment: ALL_EQUIPMENT,
    archetypes: ['Endurance Athlete', 'Hybrid Performer'],
    phases: ['foundation', 'build'],
    default_sets: 1,
    default_reps: '30min',
    default_rest_seconds: 0,
    default_rpe: 7,
    coaching_cues: ['Alternate effort spontaneously', 'Hard surges of 30-60 seconds', 'Easy jog recovery between efforts'],
    is_compound: false,
    conditioning_type: 'steady_state',
    movement_pattern: 'conditioning',
  },
  {
    name: 'Race Pace Run 5km',
    category: 'conditioning',
    equipment: ALL_EQUIPMENT,
    archetypes: ['Endurance Athlete'],
    phases: ['build', 'peak'],
    default_sets: 1,
    default_reps: '5km',
    default_rest_seconds: 0,
    default_rpe: 8,
    coaching_cues: ['Sustain your goal race pace', 'Even effort throughout', 'This is race rehearsal'],
    is_compound: false,
    conditioning_type: 'steady_state',
    movement_pattern: 'conditioning',
  },
  {
    name: 'Open Water Swim Simulation 30min',
    category: 'conditioning',
    equipment: ['full_gym'],
    archetypes: ['Endurance Athlete'],
    phases: ALL_PHASES,
    default_sets: 1,
    default_reps: '30min',
    default_rest_seconds: 0,
    default_rpe: 7,
    coaching_cues: ['Sight every 10 strokes', 'Bilateral breathing practice', 'Moderate effort, focus on form'],
    is_compound: false,
    conditioning_type: 'steady_state',
    movement_pattern: 'conditioning',
  },
]
